#!/bin/bash

# Define the login URL
LOGIN_URL="https://login.ruhr-uni-bochum.de/cgi-bin/laklogin"

# Define login credentials
USERNAME="x"
PASSWORD="x"
IPADDR="10.4.30.34"  # IP address from the reques; la ip se puede conseguir con grep en ifconfig y de ahi sacarla para que este 100% automatizado.

# Send the POST request using wget
wget --method=POST \
     --header="Content-Type: application/x-www-form-urlencoded" \
     --body-data="code=1&loginid=$USERNAME&password=$PASSWORD&ipaddr=$IPADDR&action=Login" \
     "$LOGIN_URL" -O response.html
